title: Sagnik Majumder
description: My personal blog and articles
theme: minima
sass:
  sass_dir: _sass
  style: compressed
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      css: "/assets/css/style.css"
